# -*- coding: utf-8 -*-
"""Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izDzehR0L2GbZxkza3mzwOSE2-w_VHS8
"""





a = float(input('Ingrese el valor de a?'))
b = float(input('Ingrese el valor de b?'))
c = a + b
d = a * b
print(f'el resultado de {a} + {b} es {c}')
print(f'el resultado de {a} * {b} es {d}')